FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src
COPY . .
RUN dotnet restore HistoriasPaolin.sln
RUN dotnet build src/HistoriasPaolin.Api/HistoriasPaolin.Api.csproj -c Release --no-restore
RUN dotnet tool install --global dotnet-ef --version 8.0.0
ENV PATH="${PATH}:/root/.dotnet/tools"
ENTRYPOINT ["dotnet-ef", "database", "update", "--no-build", "--configuration", "Release", "--project", "src/HistoriasPaolin.Infrastructure/HistoriasPaolin.Infrastructure.csproj", "--startup-project", "src/HistoriasPaolin.Api/HistoriasPaolin.Api.csproj"]
