<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HistoriasPaolin.Domain\HistoriasPaolin.Domain.csproj" />
    <ProjectReference Include="..\HistoriasPaolin.Contracts\HistoriasPaolin.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
